#!/usr/bin/env python

import math
import rospy
from std_msgs.msg import Float64
from sensor_msgs.msg import JointState
from simple_arm.srv import *

def at_goal():

def clamp_at_boundaries():

def move_arm():

def handle_safe_move_request():

def mover_service():
	